version: "3.9"
services:
  bot:
    command: npx nodemon
    build: .
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      - REDIS=redis://redis:6379
    env_file:
      - .env
    links:
      - redis
  redis:
    image: redis
